### ISSUE TITLE
[Feat] 메인페이지 별점 기준 숙소 추천

### ISSUE THREAD

**Issue by githyuniiee** [anonymousOrmi/simsasookbak#34]
## 어떤 기능인가요?

> 메인페이지 별점 기준 숙소 추천

## 작업 상세 내용

- [x] TODO 별점 기준 숙소 추천 api 구현
- [x] TODO 해당 부분 타임리프 구현

**Comment by www-author** [comment]
담당자 변경 : @githyuniiee  -> @BlueHarmel
